# Python建模库简介

在本书中，我专注于为使用Python进行数据分析提供编程基础。由于数据分析师和科学家经常报告花费大量时间进行数据整理和准备，因此本书的结构反映了掌握这些技术的重要性。

您用于开发模型的库取决于应用程序。许多统计问题可以通过更简单的技术来解决，例如普通的最小二乘回归，而其他问题则可能需要更高级的机器学习方法。幸运的是，Python已成为实现分析方法的首选语言之一，因此在完成本书后，您可以探索许多工具。

在本章中，我将回顾熊猫的一些功能，这些功能在您与熊猫进行数据争吵以及模型拟合和评分之间来回切换时可能会有所帮助。然后，我将简要介绍两个流行的建模工具包statsmodels和scikit-learn。由于每个项目的规模都足以保证自己拥有一本专门的书，因此，我将不做任何详尽的工作，而是将您带到两个项目的在线文档以及其他一些基于Python的有关数据科学，统计和机器学习的书。

## 13.1 pandas与标准代码之间的接口

模型开发的常见工作流程是使用熊猫进行数据加载和清理，然后再切换到建模库以构建模型本身。模型开发过程的重要部分称为机器学习中的特征工程。这可以描述从原始数据集中提取信息的任何数据转换或分析，这些信息可能在建模环境中有用。我们在本书中探讨的数据聚合和GroupBy工具经常用于功能工程环境中。

尽管“好的”功能工程的详细信息不在本书的讨论范围之内，但我将展示一些方法，以使使用熊猫进行的数据处理和建模之间的切换尽可能轻松。

pandas与其他分析库之间的接触点通常是NumPy数组。要将DataFrame转换为NumPy数组，请使用.values属性：

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.DataFrame({'x0': [1, 2, 3, 4, 5],
                     'x1': [0.01, -0.01, 0.25, -4.1, 0.],
                     'y': [-1.5, 0., 3.6, 1.3, -2]})

In [3]:
data

x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [4]:
data.columns

Index(['x0', 'x1', 'y'], dtype='object')

In [5]:
data.values

array([[ 1.  ,  0.01, -1.5 ],
       [ 2.  , -0.01,  0.  ],
       [ 3.  ,  0.25,  3.6 ],
       [ 4.  , -4.1 ,  1.3 ],
       [ 5.  ,  0.  , -2.  ]])

如您可能在前面的章节中所提到的，要转换回DataFrame，可以传递带有可选列名的二维ndarray：

In [6]:
df2 = pd.DataFrame(data.values, columns=['one', 'two', 'three'])

In [7]:
df2

one   two  three
0  1.0  0.01   -1.5
1  2.0 -0.01    0.0
2  3.0  0.25    3.6
3  4.0 -4.10    1.3
4  5.0  0.00   -2.0

> .values属性适用于数据同质的情况，例如所有数字类型。如果您具有异构数据，则结果将是Python对象的ndarray：

In [8]:
df3 = data.copy()

In [9]:
df3['string'] = ['a', 'b', 'c', 'd', 'e']

In [10]:
df3

x0    x1    y string
0   1  0.01 -1.5      a
1   2 -0.01  0.0      b
2   3  0.25  3.6      c
3   4 -4.10  1.3      d
4   5  0.00 -2.0      e

In [11]:
df3.values

array([[1, 0.01, -1.5, 'a'],
       [2, -0.01, 0.0, 'b'],
       [3, 0.25, 3.6, 'c'],
       [4, -4.1, 1.3, 'd'],
       [5, 0.0, -2.0, 'e']], dtype=object)

对于某些模型，您可能只希望使用列的子集。我建议对值使用loc索引：

In [12]:
model_cols = ['x0', 'x1']

In [13]:
data.loc[:, model_cols].values

array([[ 1.  ,  0.01],
       [ 2.  , -0.01],
       [ 3.  ,  0.25],
       [ 4.  , -4.1 ],
       [ 5.  ,  0.  ]])

一些库具有对熊猫的本机支持，并且会自动为您完成一些工作：从DataFrame转换为NumPy，并将模型参数名称附加到输出表或Series的列。在其他情况下，您将必须手动执行此“元数据管理”。

在第12章中，我们研究了熊猫的分类类型和pandas.get_dummies函数。假设我们的示例数据集中有一个非数字列：

In [14]:
data['category'] = pd.Categorical(['a', 'b', 'a', 'a', 'b'], categories=['a', 'b'])

In [15]:
data

x0    x1    y category
0   1  0.01 -1.5        a
1   2 -0.01  0.0        b
2   3  0.25  3.6        a
3   4 -4.10  1.3        a
4   5  0.00 -2.0        b

如果我们想用虚拟变量替换“类别”列，我们创建虚拟变量，删除“类别”列，然后加入结果：

In [16]:
dummies = pd.get_dummies(data.category, prefix='category')

In [17]:
data_with_dummies = data.drop('category', axis=1).join(dummies)

In [18]:
data_with_dummies

x0    x1    y  category_a  category_b
0   1  0.01 -1.5           1           0
1   2 -0.01  0.0           0           1
2   3  0.25  3.6           1           0
3   4 -4.10  1.3           1           0
4   5  0.00 -2.0           0           1

使用虚拟变量拟合某些统计模型有一些细微差别。当您有不只简单的数字列时，使用Patsy（下一节的主题）可能会更简单且更不易出错。

## 13.2 使用Patsy创建模型描述

Patsy是一个Python库，用于描述统计模型（尤其是线性模型），该模型具有基于字符串的小型“公式语法”，其灵感来自于（但不完全是）与R和S统计编程语言使用的公式语法相同。

Patsy支持在statsmodels中指定线性模型，因此，我将重点介绍一些主要功能来帮助您启动和运行。Patsy的公式是一种特殊的字符串语法，如下所示：

```
    y ~ x0 + x1
```

语法a + b并不意味着将a添加到b，而是这些是为模型创建的设计矩阵中的术语。patsy.dmatrices函数将公式字符串与数据集（可以是DataFrame或数组的dict）一起使用，并为线性模型生成设计矩阵：

In [19]:
data = pd.DataFrame({
    'x0': [1, 2, 3, 4, 5],
    'x1': [0.01, -0.01, 0.25, -4.1, 0.],
    'y': [-1.5, 0, 3.6, 1.3, -2]
})

In [20]:
data

x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [21]:
import patsy

In [22]:
y, X = patsy.dmatrices('y ~ x0 + x1', data)

In [23]:
y

DesignMatrix with shape (5, 1)
     y
  -1.5
   0.0
   3.6
   1.3
  -2.0
  Terms:
    'y' (column 0)

In [24]:
X

DesignMatrix with shape (5, 3)
  Intercept  x0     x1
          1   1   0.01
          1   2  -0.01
          1   3   0.25
          1   4  -4.10
          1   5   0.00
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'x1' (column 2)

这些Patsy DesignMatrix实例是带有附加元数据的NumPy ndarray：

In [25]:
np.asarray(y)

array([[-1.5],
       [ 0. ],
       [ 3.6],
       [ 1.3],
       [-2. ]])

In [26]:
np.asarray(X)

array([[ 1.  ,  1.  ,  0.01],
       [ 1.  ,  2.  , -0.01],
       [ 1.  ,  3.  ,  0.25],
       [ 1.  ,  4.  , -4.1 ],
       [ 1.  ,  5.  ,  0.  ]])

您可能想知道“拦截”一词的来源。这是线性模型的惯例，例如普通最小二乘（OLS）回归。您可以通过向模型添加项+ 0来抑制截距：

In [27]:
patsy.dmatrices('y ~ x0 + x1 + 0', data)[1]

DesignMatrix with shape (5, 2)
  x0     x1
   1   0.01
   2  -0.01
   3   0.25
   4  -4.10
   5   0.00
  Terms:
    'x0' (column 0)
    'x1' (column 1)

Patsy对象可以直接传递到numpy.linalg.lstsq之类的算法中，该算法执行普通的最小二乘回归：

In [28]:
coef, resid, _, _ = np.linalg.lstsq(X, y)

/Users/gaussic/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


In [29]:
coef

array([[ 0.31290976],
       [-0.07910564],
       [-0.26546384]])

In [30]:
coef = pd.Series(coef.squeeze(), index=X.design_info.column_names)

In [31]:
coef

Intercept    0.312910
x0          -0.079106
x1          -0.265464
dtype: float64

### Patsy公式中的数据转换

您可以将Python代码混合到Patsy公式中；在评估公式时，库将尝试查找您在封闭范围内使用的函数：

In [32]:
y, X = patsy.dmatrices('y ~ x0 + np.log(np.abs(x1) + 1)', data)

In [33]:
X

DesignMatrix with shape (5, 3)
  Intercept  x0  np.log(np.abs(x1) + 1)
          1   1                 0.00995
          1   2                 0.00995
          1   3                 0.22314
          1   4                 1.62924
          1   5                 0.00000
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'np.log(np.abs(x1) + 1)' (column 2)

一些常用的变量转换包括标准化（均值0和方差1）和居中（减去均值）。 Patsy为此具有内置功能：

In [34]:
y, X = patsy.dmatrices('y ~ standardize(x0) + center(x1)', data)

In [35]:
X

DesignMatrix with shape (5, 3)
  Intercept  standardize(x0)  center(x1)
          1         -1.41421        0.78
          1         -0.70711        0.76
          1          0.00000        1.02
          1          0.70711       -3.33
          1          1.41421        0.77
  Terms:
    'Intercept' (column 0)
    'standardize(x0)' (column 1)
    'center(x1)' (column 2)

在建模过程中，您可以将模型拟合到一个数据集上，然后根据另一个模型评估该模型。这可能是保留部分，也可能是以后观察到的新数据。在应用中心转换和标准化之类的转换时，使用模型基于新数据形成谓词时应格外小心。这些称为有状态转换，因为在转换新数据集时必须使用统计信息，例如原始数据集的均值或标准差。

patsy.build_design_matrices函数可以使用原始样本数据集中保存的信息将转换应用于新的样本外数据：

In [36]:
new_data = pd.DataFrame({
    'x0': [6, 7, 8, 9],
    'x1': [3.1, -0.5, 0, 2.3],
    'y': [1, 2, 3, 4]
})

In [37]:
new_X = patsy.build_design_matrices([X.design_info], new_data)

In [38]:
new_X

[DesignMatrix with shape (4, 3)
   Intercept  standardize(x0)  center(x1)
           1          2.12132        3.87
           1          2.82843        0.27
           1          3.53553        0.77
           1          4.24264        3.07
   Terms:
     'Intercept' (column 0)
     'standardize(x0)' (column 1)
     'center(x1)' (column 2)]

因为在Patsy公式的上下文中加号（+）并不意味着加法，所以当您要按名称从数据集中添加列时，必须将其包装在特殊的I函数中：

In [39]:
y, X = patsy.dmatrices('y ~ I(x0 + x1)', data)

In [40]:
X

DesignMatrix with shape (5, 2)
  Intercept  I(x0 + x1)
          1        1.01
          1        1.99
          1        3.25
          1       -0.10
          1        5.00
  Terms:
    'Intercept' (column 0)
    'I(x0 + x1)' (column 1)

Patsy在patsy.builtins模块中还有其他一些内置的转换。有关更多信息，请参见在线文档。

分类数据具有一类特殊的转换，我将在下面解释。

### 分类数据和 Patsy

可以通过许多不同方式将非数字数据转换为模型设计矩阵。对该主题的完整处理不在本书的范围内，最好与统计学课程一起研究。

当您在Patsy公式中使用非数字术语时，默认情况下会将它们转换为虚拟变量。如果存在截距，将忽略其中一个级别以避免共线性：

In [41]:
data = pd.DataFrame({
    'key1': ['a', 'a', 'b', 'b', 'a', 'b', 'a', 'b'],
    'key2': [0, 1, 0, 1, 0, 1, 0, 0],
    'v1': [1, 2, 3, 4, 5, 6, 7, 8],
    'v2': [-1, 0, 2.5, -0.5, 4.0, -1.2, 0.2, -1.7]
})

In [42]:
y, X = patsy.dmatrices('v2 ~ key1', data)

In [43]:
X

DesignMatrix with shape (8, 2)
  Intercept  key1[T.b]
          1          0
          1          0
          1          1
          1          1
          1          0
          1          1
          1          0
          1          1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)

如果从模型中省略了截距，则每个类别值的列将包括在模型设计矩阵中：

In [44]:
y, X = patsy.dmatrices('v2 ~ key1 + 0', data)

In [45]:
X

DesignMatrix with shape (8, 2)
  key1[a]  key1[b]
        1        0
        1        0
        0        1
        0        1
        1        0
        0        1
        1        0
        0        1
  Terms:
    'key1' (columns 0:2)

可以使用C函数将数值列解释为类别：

In [46]:
y, X = patsy.dmatrices('v2 ~ C(key2)', data)

In [47]:
X

DesignMatrix with shape (8, 2)
  Intercept  C(key2)[T.1]
          1             0
          1             1
          1             0
          1             1
          1             0
          1             1
          1             0
          1             0
  Terms:
    'Intercept' (column 0)
    'C(key2)' (column 1)

当您在模型中使用多个分类项时，事情可能会变得更加复杂，因为您可以包括key1：key2形式的交互项，例如，可用于方差分析（ANOVA）模型中：

In [48]:
data['key2'] = data['key2'].map({0: 'zero', 1: 'one'})

In [49]:
data

key1  key2  v1   v2
0    a  zero   1 -1.0
1    a   one   2  0.0
2    b  zero   3  2.5
3    b   one   4 -0.5
4    a  zero   5  4.0
5    b   one   6 -1.2
6    a  zero   7  0.2
7    b  zero   8 -1.7

In [50]:
y, X = patsy.dmatrices('v2 ~ key1 + key2', data)

In [51]:
X

DesignMatrix with shape (8, 3)
  Intercept  key1[T.b]  key2[T.zero]
          1          0             1
          1          0             0
          1          1             1
          1          1             0
          1          0             1
          1          1             0
          1          0             1
          1          1             1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)
    'key2' (column 2)

In [52]:
y, X = patsy.dmatrices('v2 ~ key1 + key2 + key1:key2', data)

In [53]:
X

DesignMatrix with shape (8, 4)
  Intercept  key1[T.b]  key2[T.zero]  key1[T.b]:key2[T.zero]
          1          0             1                       0
          1          0             0                       0
          1          1             1                       1
          1          1             0                       0
          1          0             1                       0
          1          1             0                       0
          1          0             1                       0
          1          1             1                       1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)
    'key2' (column 2)
    'key1:key2' (column 3)

Patsy提供了其他转换分类数据的方法，包括对具有特定顺序的术语进行转换。有关更多信息，请参见在线文档。

## 13.3 statsmodels介绍

statsmodels是一个Python库，用于拟合多种统计模型，执行统计测试以及数据探索和可视化。Statsmodels包含更多的“经典”常客统计方法，而贝叶斯方法和机器学习模型可在其他库中找到。

statsmodels中发现的一些模型包括：

- 线性模型，广义线性模型和鲁棒线性模型
- 线性混合效果模型
- 方差分析（ANOVA）方法
- 时间序列过程和状态空间模型
- 广义矩法

在接下来的几页中，我们将在statsmodels中使用一些基本工具，并探索如何将建模接口与Patsy公式和pandas DataFrame对象一起使用。

### 估计线性模型

stats模型中有几种线性回归模型，从更基本的（例如，普通最小二乘法）到更复杂的（例如，迭代地加权最小二乘）。

statsmodels中的线性模型具有两个不同的主要接口：基于数组和基于公式。这些可以通过以下API模块导入进行访问：

In [54]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

/Users/gaussic/opt/anaconda3/lib/python3.7/site-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


为了展示如何使用它们，我们从一些随机数据生成线性模型：

In [55]:
def dnorm(mean, variance, size=1):
    if isinstance(size, int):
        size = size,
    return mean + np.sqrt(variance) * np.random.randn(*size)

In [56]:
np.random.seed(12345)

In [57]:
N = 100
X = np.c_[dnorm(0, 0.4, size=N),
          dnorm(0, 0.6, size=N),
          dnorm(0, 0.2, size=N)]
eps = dnorm(0, 0.1, size=N)
beta = [0.1, 0.3, 0.5]

y = np.dot(X, beta) + eps

在这里，我写下了带有已知参数beta的“真实”模型。在这种情况下，dnorm是用于生成具有特定均值和方差的正态分布数据的辅助函数。 现在我们有了：

In [58]:
X[:5]

array([[-0.12946849, -1.21275292,  0.50422488],
       [ 0.30291036, -0.43574176, -0.25417986],
       [-0.32852189, -0.02530153,  0.13835097],
       [-0.35147471, -0.71960511, -0.25821463],
       [ 1.2432688 , -0.37379916, -0.52262905]])

In [59]:
y[:5]

array([ 0.42786349, -0.67348041, -0.09087764, -0.48949442, -0.12894109])

线性模型通常配有一个截距项，就像我们之前在Patsy中看到的那样。sm.add_constant函数可以将拦截列添加到现有矩阵：

In [60]:
X_model = sm.add_constant(X)

In [61]:
X_model[:5]

array([[ 1.        , -0.12946849, -1.21275292,  0.50422488],
       [ 1.        ,  0.30291036, -0.43574176, -0.25417986],
       [ 1.        , -0.32852189, -0.02530153,  0.13835097],
       [ 1.        , -0.35147471, -0.71960511, -0.25821463],
       [ 1.        ,  1.2432688 , -0.37379916, -0.52262905]])

sm.OLS类可以拟合普通的最小二乘线性回归：

In [62]:
model = sm.OLS(y, X)

模型的拟合方法返回包含估计的模型参数和其他诊断信息的回归结果对象：

In [63]:
results = model.fit()

In [64]:
results.params

array([0.17826108, 0.22303962, 0.50095093])

结果的汇总方法可以打印详细描述模型诊断输出的模型：

In [65]:
print(results.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.430
Model:                            OLS   Adj. R-squared (uncentered):              0.413
Method:                 Least Squares   F-statistic:                              24.42
Date:                Mon, 20 Jul 2020   Prob (F-statistic):                    7.44e-12
Time:                        06:20:37   Log-Likelihood:                         -34.305
No. Observations:                 100   AIC:                                      74.61
Df Residuals:                      97   BIC:                                      82.42
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

此处为参数名称指定了通用名称x1，x2等。假设所有模型参数都在DataFrame中：

In [66]:
data = pd.DataFrame(X, columns=['col0', 'col1', 'col2'])

In [67]:
data['y'] = y

In [68]:
data[:5]

col0      col1      col2         y
0 -0.129468 -1.212753  0.504225  0.427863
1  0.302910 -0.435742 -0.254180 -0.673480
2 -0.328522 -0.025302  0.138351 -0.090878
3 -0.351475 -0.719605 -0.258215 -0.489494
4  1.243269 -0.373799 -0.522629 -0.128941

现在，我们可以使用statsmodels公式API和Patsy公式字符串：

In [69]:
results = smf.ols('y ~ col0 + col1 + col2', data=data).fit()

In [70]:
results.params

Intercept    0.033559
col0         0.176149
col1         0.224826
col2         0.514808
dtype: float64

In [71]:
results.tvalues

Intercept    0.952188
col0         3.319754
col1         4.850730
col2         6.303971
dtype: float64

观察statsmodels如何以附加了DataFrame列名称的Series返回结果。使用公式和pandas对象时，我们也不需要使用add_constant。

给定新的样本外数据，您可以给定估计的模型参数来计算预测值：

In [72]:
results.predict(data[:5])

0   -0.002327
1   -0.141904
2    0.041226
3   -0.323070
4   -0.100535
dtype: float64

您可以探索用于统计模型中线性模型结果的分析，诊断和可视化的许多其他工具。除普通最小二乘法外，还有其他线性模型。

### 估计时间序列过程

statsmodels中的另一类模型用于时间序列分析。其中包括自回归过程，卡尔曼滤波和其他状态空间模型以及多元自回归模型。

让我们用自回归结构和噪声模拟一些时间序列数据：

In [73]:
init_x = 4

import random
values = [init_x, init_x]
N = 1000

b0 = 0.8
b1 = -0.4
noise = dnorm(0, 0.1, N)
for i in range(N):
    new_x = values[-1] * b0 + values[-2] * b1 + noise[i]
    values.append(new_x)

此数据具有参数为0.8和–0.4的AR（2）结构（两个滞后）。当您拟合一个AR模型时，您可能不知道要包括的滞后项的数量，因此您可以对模型进行一些滞后处理：

In [74]:
MAXLAGS = 5

In [75]:
model = sm.tsa.AR(values)

In [76]:
results = model.fit(MAXLAGS)

结果中的估计参数首先具有截距，然后是前两个滞后的估计：

In [77]:
results.params

array([-0.00616093,  0.78446347, -0.40847891, -0.01364148,  0.01496872,
        0.01429462])

这些模型以及如何解释其结果的更深入的细节超出了本书的范围，但是在statsmodels文档中还有很多发现。

## 13.4 scikit-learn 介绍

scikit-learn是最广泛使用和信任的通用Python机器学习工具包之一。它包含各种标准的受监督和不受监督的机器学习方法，以及用于模型选择和评估，数据转换，数据加载和模型持久性的工具。这些模型可用于分类，聚类，预测和其他常见任务。

有大量的在线和印刷资源可用于学习机器学习以及如何应用scikit-learn和TensorFlow之类的库来解决实际问题。在本节中，我将简要介绍scikit-learn API样式。

在撰写本文时，scikit-learn还没有深度的熊猫集成，尽管仍有一些附加的第三方软件包仍在开发中。不过，大熊猫对于模型拟合之前的数据集按摩非常有用。

举例来说，我使用的是Kaggle竞赛中关于泰坦尼克号上的旅客生存率的经典数据集，该数据集于1912年下沉。我们使用熊猫加载测试和训练数据集：

In [78]:
train = pd.read_csv('datasets/titanic/train.csv')
test = pd.read_csv('datasets/titanic/test.csv')

In [79]:
train[:4]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S

像statsmodels和scikit-learn这样的库通常无法提供缺失的数据，因此我们查看这些列以查看是否包含缺失的数据：

In [80]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [81]:
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

在像这样的统计数据和机器学习示例中，典型的任务是根据数据中的特征预测乘客是否会幸存。将模型拟合到训练数据集上，然后在样本外测试数据集上进行评估。

我想将Age用作预测因子，但缺少数据。有多种方法可以进行缺失数据插补，但是我将做一个简单的方法，并使用训练数据集的中位数来填充两个表中的空值：

In [82]:
impute_value = train['Age'].median()

train['Age'] = train['Age'].fillna(impute_value)
test['Age'] = test['Age'].fillna(impute_value)

现在我们需要指定模型。我添加一列IsFemale作为“性别”列的编码版本：

In [83]:
train['IsFemale'] = (train['Sex'] == 'female').astype(int)
test['IsFemale'] = (test['Sex'] == 'female').astype(int)

然后，我们确定一些模型变量并创建NumPy数组：

In [84]:
predictors = ['Pclass', 'IsFemale', 'Age']

In [85]:
X_train = train[predictors].values
X_test = test[predictors].values
y_train = train['Survived'].values

In [86]:
X_train[:5]

array([[ 3.,  0., 22.],
       [ 1.,  1., 38.],
       [ 3.,  1., 26.],
       [ 1.,  1., 35.],
       [ 3.,  0., 35.]])

In [87]:
y_train[:5]

array([0, 1, 1, 1, 0])

我不主张这是一个好的模型，也不对这些功能进行适当的设计。我们使用来自scikit-learn的LogisticRegression模型并创建一个模型实例：

In [88]:
from sklearn.linear_model import LogisticRegression

In [89]:
model = LogisticRegression()

与statsmodels类似，我们可以使用模型的fit方法将此模型拟合到训练数据：

In [90]:
model.fit(X_train, y_train)

LogisticRegression()

现在，我们可以使用model.predict对测试数据集进行预测：

In [91]:
y_predict = model.predict(X_test)

In [92]:
y_predict[:10]

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0])

如果您具有测试数据集的真实值，则可以计算准确度百分比或其他一些误差度量：

```python
    (y_true == y_predict).mean()
```

在实践中，模型训练中通常还存在许多其他复杂性层。许多模型具有可调整的参数，并且有诸如交叉验证之类的技术可用于参数调整，以避免过度拟合训练数据。这通常可以对新数据产生更好的预测性能或鲁棒性。

交叉验证通过分割训练数据以模拟样本外预测来进行工作。基于均方误差等模型准确性评分，可以对模型参数执行网格搜索。某些模型，例如逻辑回归，具有带有内置交叉验证的估计器类，例如，可以将LogisticRegressionCV类与参数一起使用，该参数指示对模型正则化参数C进行网格搜索的粒度如何：

In [94]:
from sklearn.linear_model import LogisticRegressionCV

In [96]:
model_cv = LogisticRegressionCV(Cs=10)

In [98]:
model_cv.fit(X_train, y_train)

LogisticRegressionCV()

要手动进行交叉验证，可以使用cross_val_score helper函数，该函数处理数据拆分过程。例如，要使用四个不重叠的训练数据交叉验证我们的模型，我们可以执行以下操作：

In [100]:
from sklearn.model_selection import cross_val_score

In [101]:
model = LogisticRegression(C=10)

In [102]:
scores = cross_val_score(model, X_train, y_train, cv=4)

In [103]:
scores

array([0.77578475, 0.79820628, 0.77578475, 0.78828829])

默认的评分标准取决于模型，但是可以选择一个明确的评分函数。交叉验证的模型需要更长的训练时间，但通常可以产生更好的模型性能。

## 13.5 继续你的学习

虽然我只是略过了一些Python建模库的表面，但是越来越多的框架可以用Python或使用Python用户界面实现各种统计和机器学习。

这本书的重点是数据处理，但是还有许多其他致力于建模和数据科学工具的书籍。一些优秀的是：

- Introduction to Machine Learning with Python by Andreas Mueller and Sarah
Guido (O’Reilly)
- Python Data Science Handbook by Jake VanderPlas (O’Reilly)
- Data Science from Scratch: First Principles with Python by Joel Grus (O’Reilly)
- Python Machine Learning by Sebastian Raschka (Packt Publishing)
- Hands-On Machine Learning with Scikit-Learn and TensorFlow by Aurélien
Géron (O’Reilly)

尽管书籍可以作为学习的宝贵资源，但是当基础开源软件发生变化时，书籍有时可能会过时。最好熟悉各种统计信息或机器学习框架的文档，以了解最新的功能和API。